import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#e5d3b1',
    padding: 20,
  },
  scrollView: {
    flexGrow: 1,
    backgroundColor: '#e5d3b1',
  },
  title: {
    fontSize: 26,
    fontWeight: 'bold',
    marginBottom: 20,
    marginTop: 40,
    textAlign: 'center',
    color: '#1F2937',
  },
  card: {
    backgroundColor: '#d0c0a0',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    marginHorizontal: 15,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#111827',
    marginBottom: 12,
  },
  input: {
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 8,
    padding: 10,
    marginTop: 5,
    marginBottom: 12,
    fontSize: 16,
    backgroundColor: '#fff',
  },
  label: {
    fontWeight: '600',
    color: '#1F2937',
    marginBottom: 4,
  },
  text: {
    fontSize: 16,
    color: '#374151',
    marginBottom: 4,
  },
  switchRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 8,
  },
  logoutButton: {
    backgroundColor: '#EF4444',
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 8,
    alignSelf: 'center',
    marginBottom: 20,
  },
  logoutText: {
    color: '#FFF',
    fontSize: 15,
    fontWeight: 'bold',
  },
  updateButton: {
    backgroundColor: '#4CAF50',
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 8,
    alignSelf: 'flex-end',
    marginTop: 8,
  },
  updateText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 15,
  },
});
